<?php

namespace JgeBundle\Repository;

/**
 * category_groupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class category_groupRepository extends \Doctrine\ORM\EntityRepository
{
}
