<?php

namespace JgeBundle\Repository;

/**
 * convocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class convocationRepository extends \Doctrine\ORM\EntityRepository
{
}
