JgeBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: JgeBundle\Repository\articleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: integer
            nullable: true
        title:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetime
        img:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
