JgeBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: JgeBundle\Repository\articleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetime
        img:
            type: string
            length: 255
            nullable: true

    manyToOne:
        author:
            targetEntity: JgeBundle\Entity\Member
            joinColumn:
                name: author
                referencedColumnName: id
    lifecycleCallbacks: {  }
