JgeBundle\Entity\Category_group:
    type: entity
    table: null
    repositoryClass: JgeBundle\Repository\category_groupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        manager:
            type: string
            length: '50'
        categories:
            type: array
        coach:
            type: array
        name:
            type: string
            length: '50'

    oneToMany:
        convocations:
            targetEntity: JgeBundle\Entity\Convocation
            mappedBy: category_group

    oneToMany:
        categories:
            targetEntity: JgeBundle\Entity\Category
            mappedBy: category_group

    oneToMany:
        coach:
            targetEntity: JgeBundle\Entity\Member
            mappedBy: category_group
            joinColumn: members_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
