JgeBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: JgeBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'

    oneToMany:
        members:
            targetEntity: JgeBundle\Entity\Member
            mappedBy: category
            joinColumn:
                name: members
                referencedColumnName: id

    manyToOne:
        category_group:
            targetEntity: JgeBundle\Entity\Category_group
            inversedBy: categories
            joinColumn:
                name: category_group_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
