JgeBundle\Entity\Member:
    type: entity
    table: null
    repositoryClass: JgeBundle\Repository\MemberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: '50'
        lastname:
            type: string
            length: '50'
        licenceNum:
            type: string
            length: '12'
            nullable: true
            unique: true
            column: licence_num
        dateOfBirth:
            type: date
        password:
            type: string
            length: 255
        telNumber1:
            type: string
            length: 10
        telNumber2:
            type: string
            length: 10
            nullable: true
        sex:
            type: string
            length: '1'
        shoeSize:
            type: integer
            nullable: true
            column: shoe_size
        heigth:
            type: integer
            nullable: true
        email1:
            type: string
            length: 255
        email2:
            type: string
            length: 255
            nullable: true

    manyToOne:
        category:
            targetEntity: JgeBundle\Entity\Category
            inversedBy: members
            joinColumn:
                name: category_id
                referencedColumnName: id

    manyToMany:
        convocations:
            targetEntity: JgeBundle\Entity\Convocation
            inversedBy: players
        role:
            targetEntity: JgeBundle\Entity\Role
            inversedBy: member
    manyToOne:
        category_group:
            targetEntity: JgeBundle\Entity\Category_group
            inversedBy: coach
            joinColumn:
                name: category_group_id
                referencedColumnName: id



    lifecycleCallbacks: {  }


