jge_homepage:
    path:     /
    defaults: { _controller: JgeBundle:Default:index }

jge_member:
    path:     /admin/membre
    defaults: { _controller: JgeBundle:Member:index }

jge_member_list:
    path:     /admin/membre/liste
    defaults: { _controller: JgeBundle:Member:list }

jge_member_view:
    path:     /admin/membre/detail/{id}
    defaults: { _controller: JgeBundle:Member:view }

jge_member_add:
    path:     /admin/membre/ajouter
    defaults: { _controller: JgeBundle:Member:add }

jge_member_update:
    path:     /admin/membre/modifier/{id}
    defaults: { _controller: JgeBundle:Member:update }
    requirements:
            id: \d+

jge_member_delete:
    path:     /admin/membre/supprimer/{id}
    defaults: { _controller: JgeBundle:Member:delete }
    requirements:
            id: \d+